# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='текст вопроса')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='SimpleTestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='текст ответа')),
                ('correct', models.BooleanField(default=False, verbose_name='правильный?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question')),
            ],
            options={
                'verbose_name': 'ответ (несколько вариантов)',
                'verbose_name_plural': 'ответы (несколько вариантов)',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='заголовок теста')),
                ('creation_date', models.DateField(auto_now=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'тест',
                'ordering': ['title'],
                'verbose_name_plural': 'тесты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test'),
        ),
    ]
